services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: false
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-hoangnguyen.onrender.com
